### ISSUE TITLE
Sticking to specific dogapi version is breaking existing setups

### ISSUE THREAD

**Issue by codersofthedark** [DataDog/chef-handler-datadog#118]
The following changes https://github.com/DataDog/chef-handler-datadog/blob/88b36fa5702f4f258beb9758b888c91e695ef6f0/chef-handler-datadog.gemspec#L18 is breaking existing setup. 

  ```  
Unable to activate chef-handler-datadog-0.12.3, because dogapi-1.38.0 conflicts with dogapi (= 1.36.0)
```

**Comment by AliDatadog** [comment]
Closed for inactivity.
