### ISSUE TITLE
Potential backwards incompatible change in 0.14.0

### ISSUE THREAD

**Issue by brentm5** [DataDog/chef-handler-datadog#126]
Since the upgrade today we have seen new hosts starting to throw exceptions related to the datadog handler.  All of these hosts appear to be new and are using 0.14.0.  This is the exception we are seeing

```
================================================================================
    Error executing action `enable` on resource 'chef_handler[Chef::Handler::Datadog]'
    ================================================================================
    SocketError
    -----------
    getaddrinfo: Name or service not known
```

Looking at the changelog for 0.14.0 it might be related to this dogapi change.  https://github.com/DataDog/dogapi-rb/pull/219
Not sure if its something we are doing or if its something larger but I did want to create something in case it helps someone else.

**Comment by AdilKh4n** [comment]
We ran into the same issue today. After hours of rigorous debugging, we were able to overcome this issue by creating a new DHCP options set attached to the VPC, which includes domain-name entry for <aws-region>.compute.internal. FYI @brentm5 
This should work with version 0.14.0.

**Comment by KSerrania** [comment]
Hi @brentm5,

Thanks for the report!

To help us confirm that https://github.com/DataDog/dogapi-rb/pull/219 is indeed responsible for this change, could you give us the output and status code of `hostname -f` on a host where your chef run failed?

**Comment by brentm5** [comment]
So I ended up fixing this yesterday by setting the following in our datadog cookbook: `override['datadog']['chef_handler_version'] = '0.13.0'`.  I was able to launch a vanilla host and run the commands before chef ran on it and that provided the following:

```
hostname -f
hostname: Unknown host

hostname
ip-10-10-10-10
```

**Comment by KSerrania** [comment]
Thanks for the answer!

Comparing the behavior before and after this change:
- with 0.13.0, `hostname -f` fails with `hostname: Unknown host`, leaving `@@hostname` empty but not raising an exception.
- with 0.14.0, `hostname -f` still fails, but non-0 error codes are handled as exceptions are, thus triggering the `Addrinfo.getaddrinfo` line (which also fails).

Given the code change, this new behavior is thus expected. However, we should try to recover better from this error (eg. try `hostname` if `Addrinfo.getaddrinfo` also fails) in dogapi.

Side question: for this host, what hostname is reported by the chef handler events when using `0.13.0`?

**Comment by albertvaka** [comment]
I've made a change to try `hostname -s` if everything else fails.

https://github.com/DataDog/dogapi-rb/pull/242

Can you give it a try @brentm5? Since I can't reproduce the error, I haven't been able to test if the fix works, so your help would be greatly appreciated :)

**Comment by brentm5** [comment]
> Given the code change, this new behavior is thus expected. However, we should try to recover better from this error (eg. try hostname if Addrinfo.getaddrinfo also fails) in dogapi.

Although it might be expected with the new behavior this caused entire chef runs to fail.  That sounds like a bug, I would expect the handler to fail gracefully in this scenario.

**Comment by albertvaka** [comment]
@brentm5 Can you give the following PR a try? Since I can't reproduce the error, I haven't been able to test if the fix works, so your help would be greatly appreciated :)

DataDog/dogapi-rb#242

**Comment by brentm5** [comment]
I was out last week and will try to run a similar command this week.  One thing that does stand out to me is that right now the hostname is found via two different methods.  Essentially the reporter defers to the dogapi-rb to get the hostname and then the handler finds the hostname from chef. 

You can see the clients are initialized and a nil hostname is passed in to start, this means that the dogapi-rb code can cause chef runs to fail.

https://github.com/DataDog/chef-handler-datadog/blob/master/lib/chef/handler/datadog.rb#L135

Wouldn't it make sense to use the value from here instead to set the host ?

https://github.com/DataDog/chef-handler-datadog/blob/master/lib/chef/handler/datadog.rb#L47

**Comment by brentm5** [comment]
I was just able to setup a test host from the original failure scenario and test with `hostname -s` that did return a valid response with a valid response code.

**Comment by albertvaka** [comment]
🎉 Happy to hear that! Thanks a lot for your help 🙇 

The next steps for us, then, are:
- Release new version of dogapi-rb with the fix
- Bump the version of dogapi-rb used in chef-handler-datadog
- Merge #128
- Release chef-handler-datadog

**Comment by albertvaka** [comment]
Release done with the bumped dogapi-rb 👍  Feel free to reopen this issue if you run into more problems.
