### ISSUE TITLE
Collect non-runlist roles

### ISSUE THREAD

**Issue by sethrosenblum** [DataDog/chef-handler-datadog#53]
When collecting roles to add as tags, we use the node's run list:
```
node.run_list.roles.map! { |role| 'role:' + role }
```
https://github.com/DataDog/chef-handler-datadog/blob/master/lib/chef/handler/datadog.rb#L222

This means that we don't get tags for the roles that are inherited by other roles.  To get these we should use `node.roles` or the union of the two.

**Comment by miketheman** [comment]
Closing, as it's still unclear how these dimensions would work properly.
