### ISSUE TITLE
Question: properly set hostname

### ISSUE THREAD

**Issue by arosenhagen** [DataDog/chef-handler-datadog#56]
currently the chef-handler reports under the IP of the node. It would be nice to have a setting to set the hostname so we don't have an additional instance in datadog which only meters the chef runs.

or am I missing something here?

**Comment by miketheman** [comment]
Hi @arosenhagen,

When you state that the Handler reports the IP of the node, I'm curious - are your Chef Node objects names or IP addresses?
Here's the method and logic that is used when the Handler selects the hostname to use:
https://github.com/DataDog/chef-handler-datadog/blob/f5f4691db9d9bcacba62a163f4361243aeb82ea9/lib/chef/handler/datadog.rb#L245-L264

The logic is tested here, in a few different cases - on EC2 with flag enabled, no config specified, etc
https://github.com/DataDog/chef-handler-datadog/blob/f5f4691db9d9bcacba62a163f4361243aeb82ea9/spec/datadog_spec.rb#L99-L182

See #41 for the original discussion and associated code changes.

I think there's still an outstanding need for a method to set the Handler's hostname config in a sane manner from the datadog cookbook.

**Comment by miketheman** [comment]
@arosenhagen We never heard back from you, and it's been over year since we discussed this. I'm going to close this issue, please reopen it if you have some more details you'd like to discuss.
