### ISSUE TITLE
Support use of DataDog agent proxy settings for report handler

### ISSUE THREAD

**Issue by datwiz** [DataDog/chef-handler-datadog#64]
2 part change to both chef-handler-datadog and the chef-datadog  cookbook recipe dd-handler.rb to enable support for use of the agent proxy values being set in the cookbook.  We tunnel datadog traffic via a special proxy, but use local caching gem servers.  Setting the proxy env variables before the chef run causes the gem install to fail.  Not setting the proxy env variables before the chef run causes the handler to fail.
The combined proposed pull requests across the 2 projects enables the use of the proxy settings being set for the agent to be used by the handler.

**Comment by jaredbonobos** [comment]
is this going to go out soon?
