### ISSUE TITLE
Datadog host mismatch error

### ISSUE THREAD

**Issue by apratina** [DataDog/chef-handler-datadog#67]
We see a warning that the tags were unable to be added in the initial chef-client run, but will be added in future runs. This is being run in the section of the datadog chef handler found here: https://github.com/DataDog/chef-handler-datadog/blob/master/lib/chef/handler/datadog.rb#L50, so pausing before updating these tags may allow for the host to always be created on datadog end before trying to push the tags.

**Comment by miketheman** [comment]
Resolved via #80 and release in 0.8.0.
