### ISSUE TITLE
Issue with handler not reporting metrics on chef failures

### ISSUE THREAD

**Issue by bigbam505** [DataDog/chef-handler-datadog#68]
We recently ran into an issue on windows where a chef failure caused the handler to also fail and not report metrics.  The code in question was [this](https://github.com/DataDog/chef-handler-datadog/blob/master/lib/chef/handler/datadog_chef_metrics.rb#L46-L49).  I do not know how it got into the state but to give some more information it was because of the firefox, more importantly [Here](https://github.com/tas50/Firefox/blob/master/libraries/default.rb#L33) when it was trying to reach out to this url https://download-installer.cdn.mozilla.net/pub/firefox/releases/latest/win32/en-US .  The fact that this failed horribly isn't the stupid part but rather that datadog failed to report the failures.  Probably just needs some null checks.

**Comment by miketheman** [comment]
Resolved via #69 and released in 0.8.0. Thanks!
