### ISSUE TITLE
Please allow for a blacklist/whitelist when it comes to the chef tags that DataDog sends with it's data.

### ISSUE THREAD

**Issue by ABrehm264** [DataDog/chef-handler-datadog#85]
I have several tags that are super useful for me to have in chef, but not so useful when it's sent to DataDog to be read by my developers, since they end up turning into noise. Would it be possible to blacklist/whitelist the tags the chef sends using a regex or something?

Example:
My server has these tags:
- ENV_PRODUCTION
- APP_APPLICATION1
- APP_APPLICATION2
- APP_APPLICATION3

When events or event log entries are sent, every one is tagged with every single chef tag associated with the box.
- DD Event tags: [ENV_PRODUCTION, APP_APPLICATION1, APP_APPLICATION2, APP_APPLICATION3]
- Data: There was a problem in Application1, please fix it.

I would like to make it so that it either sends no chef tags or it only sends the ENV_ tag.

**Comment by ABrehm264** [comment]
I think this could be a way to fix it, but I'm not sure. (note this is ruby and c# mixed together cause I'm not all that fluent with ruby yet)

  # this is defined somewhere
 Regex regexBlackList = new Regex(string_that_I_pass_in_from_somewhere, RegexOptions.CaseInsensitive) #100% totally c# :P
 
  def node_tags
    return [] unless @node.tags
    output = @node.tags.map { |tag| "#{@tag_prefix}#{tag}" }
    # below is c#-ish pseudo code since I don’t know ruby all that well.
    return output if (regexBlackList == nil)
 
    return output.Where(o => !regexBlackList.IsMatch(o)) # is the black list is set, only return the items which aren’t specified by it.
  End
 
So I guess I have several questions:
1)       Would this fix the issue where I have EventViewer and Custom datadog events coming through with all my chef tags
2)       Are you all cool with that approach?
3)       If you’re cool with this approach, how would you like me to pass in the black list.

**Comment by ABrehm264** [comment]
I'd need these questions answered though.
1)       Would this fix the issue where I have EventViewer and Custom datadog events coming through with all my chef tags
2)       Are you all cool with that approach?
3)       If you’re cool with this approach, how would you like me to pass in the black list.

**Comment by TheJeremyGray** [comment]
:+1:

**Comment by TheJeremyGray** [comment]
This is the behavior that i see after an application sends a log to the datadog agent.  Only 1 of the redacted app_ keys is relevant.  The end result is, when I try to search for app_myapp, I see all the errors for all the applications on the server.

![image](https://cloud.githubusercontent.com/assets/1553086/17405332/124141f6-5a2d-11e6-9133-42cce02922f5.png)

**Comment by catalintomescu** [comment]
This would definitely clean up the tags list.

**Comment by RAMunch** [comment]
This would make the tags in DD so much more useful to me! Right now they are more hurtful than they are helpful.
:+1:

**Comment by olivielpeau** [comment]
Thanks @ABrehm264 for your feedback!

> 1) Would this fix the issue where I have EventViewer and Custom datadog events coming through with all my chef tags

Your approach would fix this indeed. The environment and role tags (`env:` and `role:`) wouldn't be affected by the filter/regex.

> 2) Are you all cool with that approach?

Sounds reasonable yes!

> 3) If you’re cool with this approach, how would you like me to pass in the black list regex.

You could pass the regex to the `DatadogChefTags` instance [here](https://github.com/DataDog/chef-handler-datadog/blob/v0.9.0/lib/chef/handler/datadog.rb#L53-L59), from the `config` object. The `config` is generally passed to the handler in the Chef recipe that sets up the handler, in our case that would be in `chef-datadog`: see https://github.com/DataDog/chef-datadog/blob/v2.4.0/recipes/dd-handler.rb#L41-L60.


And just to be extra clear: filtering the list of tags that's sent to Datadog would not only affect the event tags but also the host-level tags. This means that all the metrics and service checks coming from the host/Agent would also stop being tagged with these excluded tags.

Let me know if you have any questions or if you need help with the implementation, thanks!

**Comment by ABrehm264** [comment]
@olivielpeau, I think I got it, can you check over it and let me know if it's good? If it's good, what are the next steps?

**Comment by ABrehm264** [comment]
@olivielpeau, I changed the test name that you asked be changed per https://github.com/DataDog/chef-handler-datadog/pull/86/files#r75447388.

Thanks,
Alex
